// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1lyDCKK67FfasDCsbC3LhXGsNNJUfW64',
    appId: '1:786785765965:web:6db33409ccc546765aaa04',
    messagingSenderId: '786785765965',
    projectId: 'unisphere-2b0c2',
    authDomain: 'unisphere-2b0c2.firebaseapp.com',
    storageBucket: 'unisphere-2b0c2.firebasestorage.app',
    measurementId: 'G-Q8K5QRJ6P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjw50Fb9X86SOlaHiPMSryuyBu15oEOAI',
    appId: '1:786785765965:android:796b00bde38bd94c5aaa04',
    messagingSenderId: '786785765965',
    projectId: 'unisphere-2b0c2',
    storageBucket: 'unisphere-2b0c2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1lyDCKK67FfasDCsbC3LhXGsNNJUfW64',
    appId: '1:786785765965:web:1456d11bc8708bf05aaa04',
    messagingSenderId: '786785765965',
    projectId: 'unisphere-2b0c2',
    authDomain: 'unisphere-2b0c2.firebaseapp.com',
    storageBucket: 'unisphere-2b0c2.firebasestorage.app',
    measurementId: 'G-VKB0K7TKDR',
  );
}
